version: "3.9"

services:
  client1:
    build: .
    healthcheck:
      test: ["CMD", "sleep", "1"]

  client2:
    build: .
    healthcheck:
      test: ["CMD", "sleep", "1"]
    depends_on:
      client1:
        condition: service_healthy

  client3:
    build: .
    healthcheck:
      test: ["CMD", "sleep", "1"]
    depends_on:
      client2:
        condition: service_healthy
